server:
  port: 8085
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: 'jdbc:postgresql://localhost:35432/db_inventory'
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  kafka:
    consumer:
      bootstrap-servers: 'localhost:9092'
      group-id: ecommerce
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
