server:
  port: 8085
spring:
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: 'jdbc:postgresql://localhost:35432/inventory'
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  kafka:
    consumer:
      bootstrap-servers: 'localhost:9092'
