server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:35432/product
    driver-class-name: org.postgresql.Driver
    username: john
    password: ecommerce
