spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: postgres://localhost:35432/product?useTimezone=true&setTimezone=GMT
    driver-class-name: org.postgresql.Driver
    name: john@ecommerce.com
    password: ecommerce
 
