spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: 'jdbc:postgresql://localhost:35432/customer'
    driver-class-name: org.postgresql.Driver
    username: john
    password: ecommerce
