server:
  port: 8084
spring:
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialec
  datasource:
    url: 'jdbc:postgresql://localhost:35432/customer'
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
